name: Deploy Next.js Application

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'
          cache: 'npm'
          
      - name: Install dependencies
        run: npm ci
        
      - name: Build application
        run: npm run build
        
      # Bỏ qua bước test vì không có script test
      # - name: Run tests
      #   run: npm test
        
      - name: Deploy to GitHub Pages
        if: success() && github.ref == 'refs/heads/main'
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: out # Thư mục sau khi build
          branch: gh-pages
          token: ${{ secrets.deployee }}
